<?php /*********************************************************************
If you edit this file don't forget to edit the file forgot_text to match!!!!
*************************************************************************/?>
<html>
<body>
<p>A password reset has been requested for your email address <?php echo $this->UserRow->user_nm; ?>.</p>
<p>If you did not request this password reset, please reply to this email, and let us know.</p>
<p>If you wish to reset your password, click the following link:</p>
<p><a href="http://<?php echo $this->reset_link; ?>">http://<?php echo $this->reset_link; ?></a></p>
Regards,<br>
<?php echo $this->admin_name; ?><br/>
<?php echo $this->admin_email; ?><br/>
<?php echo $this->admin_number; ?><br/>
</body>
</html>