<html>
<body>
Access to <?php echo $this->domain; ?> was requested from IP Address <?php echo $this->ip_address; ?>. <br/><br/>
                
User Name: <?php echo $this->name; ?><br/>
User Email: <?php echo $this->email; ?><br/>
User Phone: <?php echo $this->phone; ?><br/><br/>
                        
Maanger's Name: <?php echo $this->mgr_name; ?><br/>
Manager's Email: <?php echo $this->mgr_email; ?><br/>
Manager's Phone: <?php echo $this->mgr_phone; ?><br/><br/>
                        
Special Instructions:<br/>
<pre>
<?php echo $this->instructions; ?>
</pre>
                
</body>
</html>