
<div style="width:99%;" class="row">

	<div class="col-md-10 col-md-offset-1">
		<div style="padding:15px;">
			<table  class="table display" id="projects">
				<thead>
					<tr>
						<th nowrap="nowrap">Project Name</th>
						<th width="30%" class="hidden-xs hidden-sm">Description</th>
						<th nowrap="nowrap" class="">Project Lead</th>
						<th nowrap="nowrap" class="hidden-xs">Team
							Members</th>
	    	<?php if ($this->role=='administrator') { ?>
	    	<th nowrap="nowrap"></th>
	    	<?php } ?>
	    </tr>
				</thead>

				<tbody>
	    <?php foreach($this->projects as $Row) {?>
	      <tr><?php $href=$this->url(array('controller'=>'grid','action'=>'coding','project_id'=>$Row['project_id']), null, TRUE); ?>
	
	        <td nowrap="nowrap" style="vertical-align: top;"><a title="Open Project"
							href="<?php echo $href ?>"><?php echo trim($Row['project_txt']); ?></a></td>
						<td class="hidden-xs hidden-sm" style="vertical-align: top;"><?php echo nl2br(trim($Row['project_desc'])); ?></td>
						<td nowrap="nowrap" class="" style="vertical-align: top;">
							<a title="Send Email" href="mailto:<?php echo (($Row['project_lead']!=null)?trim($Row['project_lead']):" "); ?>?subject=Regarding <?php echo trim($Row['project_txt']); ?>">
								<?php echo (($Row['project_lead']!=null)?trim($Row['project_lead']):" "); ?>
							</a> 
						</td>
						<td nowrap="nowrap" class="hidden-xs">
	
	            <?php
						
						$i = 0;
						foreach ( $Row ['team_members_assigned'] as $member ) {
							if ($i != 0)
								echo ", ";
							if ((($i % 3) == 0) && ($i != 0))
								echo "<br />";
							$i ++; ?>
							<a title="Send Email" href="mailto:<?php echo $this->users [$member->uid] ['user_nm']; ?>?subject=Regarding <?php echo trim($Row['project_txt']); ?>">
								<?php echo $this->users [$member->uid] ['user_nm']; ?>
							</a> 
							<?php 
						}
				?>
			
	        </td>
	        <?php if ($this->role=='administrator') { ?>
	        <td nowrap style="vertical-align: top;">
	        	<a title="Edit" href="/index/edit/project_id/<?=$Row['project_id']?>">
					<i class="icon-pencil"></i>
				</a> &nbsp; &nbsp; &nbsp;
				<a title="Archive" href="/index/archive/project_id/<?=$Row['project_id']?>">
					<i class="icon-archive"></i>
				</a> &nbsp; &nbsp; &nbsp;
				<a title="Delete" href="/index/delete/project_id/<?=$Row['project_id']?>"
					onclick="return confirm('WARNING! \n\nAre you sure you want to delete this project? \n\n')">
					<i class="icon-trash"></i>
				</a>
			</td>
	        <?php } ?>
	      </tr>
	    <?php } ?>
	  </tbody>
			</table>
		</div>
	</div>

</div>

<script type="text/javascript" charset="utf-8">
var winW = 630, winH = 460;
if (document.body && document.body.offsetWidth) {
 winW = document.body.offsetWidth;
 winH = document.body.offsetHeight;
}
if (document.compatMode=='CSS1Compat' &&
    document.documentElement &&
    document.documentElement.offsetWidth ) {
 winW = document.documentElement.offsetWidth;
 winH = document.documentElement.offsetHeight;
}
if (window.innerWidth && window.innerHeight) {
 winW = window.innerWidth;
 winH = window.innerHeight;
}
  $(document).ready(function() {
    $('#projects').dataTable( {
      "sScrollY": (winH-195)+"px",
      "bPaginate": false,
      "bSortClasses": false,
      "aaSorting": [],
      "sWrapper": "dataTables_wrapper form-inline"
      <?php if ($this->role=='administrator') { ?>
      ,"aoColumnDefs": [{ "asSorting": [  ], "aTargets": [ 4 ] }]
      <?php } ?>
    } );
  } );

	
</script>