<ul class="nav navbar-nav navbar-right">

<li class="dropdown"><a href="#" class="dropdown-toggle"
				data-toggle="dropdown"><i class="icon-cogs"></i> <b class="caret"></b></a>
				<ul class="dropdown-menu">


<?php
// // See _initNavigation() in the Bootstrap.php file.
foreach ($this->menu as $element)
{
	$uri=$element['uri'];
	$label = $element['label'];
	
	echo "<li>\n";
	echo "	<a href='$uri'>$label</a>\n";
	echo "</li>\n";	
}
?>
	<li class="divider"></li>
	<li>
		<a href='<?php echo $this->ProfileURL; ?>'>Change Password</a>
	</li>
	<li>
		<a href='<?php echo $this->LogInOutURL; ?>'>Sign Out</a>
	</li>
</ul>
</ul>
