<style>
    
#leftgrid .slick-viewport {
    overflow-y: hidden !important;
}

#linkgrid .slick-viewport {
    overflow-y: hidden !important;
}
</style>

<script>



//window.onscroll = function (event) {
//	  console.log("Scroll");
//	}


var dataOptions = {"multiColumnSort":true,"DataModel":{},"project_id":"21","table_name":"grid_link","jsonrpc":"\/gap\/rpc\/project_id\/21","gridName":"leftgrid"};
Data =  new PHPSlickGrid.JSON.GapDataCache(dataOptions);

Data.onRowCountChanged.subscribe(function (e, args) {
	
    leftgrid.updateRowCount();
    leftgrid.render();

    linkgrid.updateRowCount();
    linkgrid.render();

    rightgrid.updateRowCount();
    rightgrid.render();
});


Data.onRowsChanged.subscribe(function (e, args) {

	leftgrid.invalidateRows(args.rows);
	leftgrid.render();
	
	linkgrid.invalidateRows(args.rows);
	linkgrid.render();

	rightgrid.invalidateRows(args.rows);
	rightgrid.render();
});

function GapInvalidate() {

	Data.invalidate();
	
	leftgrid.invalidate();
	leftgrid.render();
	
	linkgrid.invalidate();
	linkgrid.render();

	rightgrid.invalidate();
	rightgrid.render();
}

var dataLinkOptions = {"multiColumnSort":true,"DataModel":{},"project_id":"21","table_name":"grid_link","jsonrpc":"\/gap\/rpc\/project_id\/21","gridName":"linkgrid"};
linkgridData = new PHPSlickGrid.JSON.GapDataCacheTable(dataLinkOptions,Data);

var dataLeftOptions = {"multiColumnSort":true,"DataModel":{},"project_id":"21","table_name":"grid_left","jsonrpc":"\/gap\/rpc\/project_id\/21","gridName":"leftgrid"};
leftgridData = new PHPSlickGrid.JSON.GapDataCacheTable(dataLeftOptions,Data);

var dataRightOptions = {"multiColumnSort":true,"DataModel":{},"project_id":"21","table_name":"grid_right","jsonrpc":"\/gap\/rpc\/project_id\/21","gridName":"rightgrid"};
rightgridData = new PHPSlickGrid.JSON.GapDataCacheTable(dataRightOptions,Data);
		
</script>

<div id='phpslickgrid' style="height:100%;">

	<div id='leftgrid2' style="overflow: hidden; height:100%; float:left; width:40%;">
		<div id='left_c' style="height:100%;">
			<?php echo $this->PHPSlickgridGap("leftgrid",null,$this->GridColumnConfigurationLeft,$this->GridConfigurationLeft); ?>
		</div>
		<div style="width:100%;visibility:visible;height:17px;background-color: #f2f2f2;">
			<div style='float:right;padding-right:10px;'><?php echo $this->load_left; ?></div>
		</div>
	</div>
	
	<div id='linkgrid' style="overflow: auto; height:100%; width: 100px; float:left;border-left:3px solid blue;border-right:3px solid blue;">
		<?php echo $this->PHPSlickgridGap("linkgrid",null,$this->GridColumnConfiguration,$this->GridConfiguration); ?>
	</div>
 
	<div id='rightgrid2' style="overflow: auto; height:100%;float:left; width: 40%;">
		<div id='right_c' style="height:100%;">
			<?php echo $this->PHPSlickgridGap("rightgrid",null,$this->GridColumnConfigurationRight,$this->GridConfigurationRight); ?>
		</div>
		<div style="width:100%;visibility:visible;height:17px;background-color: #f2f2f2;">
			<div style='float:right;padding-right:10px;'><?php echo $this->load_right; ?></div>
		</div>
	</div>
	
</div>

<script>
var total_width = $( window ).width();
var center_width = 100;
var left_width=((total_width-100)/2);
var right_width=((total_width-100)/2)-(total_width-(center_width+left_width+((total_width-100)/2)))-3-3;
//console.log(width);
$("#leftgrid2").width(left_width);
$("#rightgrid2").width(right_width);
$('div.slick-viewport:last').css({"overflow-y" : 'auto !important'});

var leftheight = $("#left_c").height();
$("#left_c").height(leftheight-17);
leftgrid.resizeCanvas();

var rightheight = $("#right_c").height();
$("#right_c").height(rightheight-17);
rightgrid.resizeCanvas();
//$("#leftgrid").height(leftheight-20);




 rightgrid.onScroll.subscribe(function(e,args){
     // console.log(e);
     // console.log(args);
 	linkgrid.scrollPort(args.scrollTop);
 	leftgrid.scrollPort(args.scrollTop);
 });



</script>