<div style="witdh:100%; height:100%;background-color:#f2f2f2;">
<form  enctype="application/x-www-form-urlencoded" action="" method="post" >
    
	<div id="view-content" style="position:absolute;top: 35%;left: 50%;margin-top: -50px;margin-left: -140px;">
		<table style="width:280px;height:100px;border:1px solid;background-color:white;">
			<tr>
				<td style="white-space: nowrap;">Email:</td>
				<td><?php echo $this->formText("email",$this->email,array('style'=>'width:200px')); ?></td>
			</tr>
			<tr>
				<td colspan="2">
					<div style='float:left;'><?php echo $this->formSubmit("forgot","Email Password Reset"); ?></div>  
					<div style='float:right;'><?php echo $this->formSubmit("cancel","Cancel",array('onclick'=>'this.form.action="/login";')); ?></div>
				</td>
		    </tr>
		</table>
	</div>
	
</form>
</div>
<script>
window.onload = function() {
	  document.getElementById("email").focus();
};
	
<?php echo $this->message; ?>

</script>