<div style="witdh:100%; height:100%;background-color:#f2f2f2;">
<form enctype="application/x-www-form-urlencoded" action="" method="post" >

    <?php if ($this->message!='') {?>
    <div id="view-message" style="padding:5px; width:268px;position:absolute;top: 20%;left: 50%;margin-top: -50px;margin-left: -140px;border:1px solid;border-color:red;background-color:white;word-wrap:break-word;overflow:auto;">
    <?php echo $this->message; ?>
    </div>
    <?php } ?>
    
	<div id="view-content" style="position:absolute;top: 35%;left: 50%;margin-top: -50px;margin-left: -140px;">
		<table style="width:280px;height:100px;border:1px solid;background-color:white;">
			<tr>
				<td>Email:</td><td><?php echo $this->formText("email",$this->email,array('style'=>'width:200px')); ?></td>
			</tr>
			<tr>
				<td>Password:</td><td><?php echo $this->formPassword("password",$this->password,array('style'=>'width:200px')); ?></td>
			</tr>
			<tr>
				<td colspan="2">
					<div style='float:left;'><?php echo $this->formSubmit("login","Login"); ?></div>
					<div style='float:right;'>
						<div style='float:left;'><?php echo $this->formSubmit("forgot_password","Forgot Password",array('onclick'=>'this.form.action="/login/forgot";')); ?></div>
						<div style='float:left;'><?php echo $this->formSubmit("request_access","Request Access",array('onclick'=>'this.form.action="/login/request";')); ?></div>
					</div>
				</td>
		    </tr>
		</table>
	</div>
	
</form>
</div>
<script>
window.onload = function() {
	  document.getElementById("email").focus();
	};
</script>