<div style="witdh:100%; height:100%;background-color:#f2f2f2;">
<form  enctype="application/x-www-form-urlencoded" action="" method="post" >

    <?php if ($this->message!='') {?>
    <div id="view-message" style="padding:5px; width:338px;position:absolute;top: 20%;left: 50%;margin-top: -50px;margin-left: -140px;border:1px solid;border-color:red;background-color:white;word-wrap:break-word;overflow:auto;">
    <?php echo $this->message; ?>
    </div>
    <?php } ?>
    
	<div id="view-content" style="position:absolute;top: 40%;left: 50%;margin-top: -50px;margin-left: -140px;">
		<table style="width:350px;height:100px;border:1px solid;background-color:white;">
		    <tr>
				<td style="white-space: nowrap;">Your Name*:</td><td><?php echo $this->formText("name",$this->name,array('style'=>'width:150px')); ?></td>
			</tr>
			<tr>
				<td style="white-space: nowrap;">Your Email Address*:</td><td><?php echo $this->formText("email",$this->email,array('style'=>'width:150px')); ?></td>
			</tr>	
			<tr>
				<td style="white-space: nowrap;">Your Phone Number:</td><td><?php echo $this->formText("phone",$this->phone,array('style'=>'width:150px')); ?></td>
			</tr>
			<tr>
				<td style="white-space: nowrap;">Your Manager's Name:</td><td><?php echo $this->formText("mgr_name",$this->mgr_name,array('style'=>'width:150px')); ?></td>
			</tr>
			<tr>
				<td style="white-space: nowrap;">Your Manager's Email Address*:</td><td><?php echo $this->formText("mgr_email",$this->mgr_email,array('style'=>'width:150px')); ?></td>
			</tr>
			<tr>
				<td style="white-space: nowrap;">Your Manager's Phone Number:</td><td><?php echo $this->formText("mgr_phone",$this->mgr_phone,array('style'=>'width:150px')); ?></td>
			</tr>
			<tr>
				<td style="white-space: nowrap;vertical-align:top;">Special Instructions:</td><td><?php echo $this->formTextarea("instructions",$this->instructions,array('style'=>'resize: none; width:150px;height:60px;')); ?></td>
			</tr>
			<tr>
				<td style="white-space: nowrap;vertical-align:top;" colspan='2'>* Required</td>
			</tr>
			<tr>
				<td><?php echo $this->formSubmit("request","Request Access"); ?>  </td>
				<td style="text-align: right;">
				<?php echo $this->formSubmit("cancel","Cancel",array('onclick'=>'this.form.action="/login";')); ?></td>
		    </tr>
		</table>
	</div>
	
</form>
</div>
<script>
	window.onload = function() {
	  document.getElementById("name").focus();
	};

	<?php echo $this->js; ?>
	
</script>
