<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
	<head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  		
  		<?php echo (isset($this->metaCustom))?$this->metaCustom:""; ?>
  		
        <?php echo $this->headTitle(); ?>
        
        <?php echo $this->headLink(); ?>
        
        <?php echo $this->headStyle(); ?>
        
        <?php echo $this->headScript(); ?>
        
	</head>
<body>
<div id="header" <?php echo $this->watermark; ?>>
<?php echo $this->render('header.phtml');?>
</div>
<div id="mainContent">
<?php echo $this->layout()->content; ?>
</div>
<div id="footer">
<?php echo $this->render('footer.phtml');?>
</div>
</body>
<?php echo $this->inlineScript(); ?>
</html>
